### PR TITLE
adding a template

### PR DESCRIPTION
**Pull request by nwstephens**
added a simple template to the registration app. should be very easy to modify if you need to make adjustments. see a live example here: http://colorado.rstudio.com:3838/nathan/classroom/

### CODE REVIEW

**Comment by nwstephens** [comment]
Note: the classroom password on the sample app is `abc123`.

**Comment by nwstephens** [comment]
The admin button is not formatted properly. I couldn't figure out how to get it to pick up the formatting without it being dynamic. I think the dynamically appearing action is not necessary and really got in my way as an admin. I would leave it on the UI always and make it require an admin password. That will make it a lot easier for all the instructors at RStudio to use this page.

**Comment by colearendt** [comment]
@nwstephens and @Skeptycal - please delete or rename your forks from this orphaned repository and fork instead from https://github.com/colearendt/classroom-server or the (now correctly organized) proper upstream https://github.com/sol-eng/classroom-server

**Comment by colearendt** [comment]
Also, these changes have been merged to master on https://github.com/sol-eng/classroom-server. Thanks Nathan!

**Pull request closed without merging**
